name: auto-check-in


on:
  schedule:
    - cron: 45 1 * * *

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: config environment
        run: npm install -g
      
      - name: run
        run: node index
        env:
          COOKIE: ${{secrets.COOKIE}}
          TOKEN: ${{secrets.TOKEN}}
