name: auto-check-in


on:
  push:
  schedule:
    - cron: '0 15 * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      # 配置环境
      - name: config environment
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        run: npm install -g
        env:
          COOKIE: ${{ secrets.COOKIE }}
      - name: run
        run: node index
